word_options = [
    
    'abandon',
    'ability' ,
    'above',
    'abroad',
    'absent' ,
    'absolute' ,
    'abstract',
    'abuse',
    'abusive',
    'academic',
    'accede' ,
    'acceptance'
    'access',
    'accident',
    'bachelor',
    'blackboard',
    'background',
    'biology',
    'backup',
    'backward',
    'bacteria',
    'baggage',  
    'balance',
    'bandage',
    'banker',
    'bankruptcy',
    'barber',
    'calculate',
    'calendar',
    'camera' 
    'campaign',
    'campus',
    'cancel',
    'candidate',
    'capacity',
    'capital',
    'captain',
    'capture',
    'condescending',
    'damage',
    'dangerous',
    'daughter',
    'dawn',
    'downfall'
    'delicacy',
    'detangle',
    'emerald'
    'management',
    'manager',
    'manner', 
    'manufacture',
    'multiply',
    'vessel',
    'vestige',
    'veterinarian',
    'victim', 
    'victory',
    'painting',
    'parallel',
    'paragraph',
    'patronise',
    'spouse',
    'sarcasm',
    'synonym',
    'superior',
    'technique',
    'technology',
    'teammate',
    'zealous',
    'zipper'

]